# Generated by Django 5.0.6 on 2024-07-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
